### PR TITLE
Don't replace the word `keyframes` when its already there

### PR DESCRIPTION
**Pull request by donavon**
OK, this is minor on the grand scheme of things that need to be fixed in the world, but still... Shouldn't we make the world a better place when we can?

### CODE REVIEW

**Comment by kof** [comment]
are tests passing?

**Comment by donavon** [comment]
I'm on a Windows machine. Builds/tests don't work there. I'll leave that to you or can try tonight on my Mac.

**Comment by donavon** [comment]
OK, so I temporarily hacked the `package.json` to say:
```
"build:max": "set NODE_ENV=development && webpack src/index.js dist/jss-vendor-prefixer.js"
```
then ran `npm test` and they PASS. :checkered_flag:

**Comment by kof** [comment]
thanks

**Pull request merged**
